type Category = string;
export const categories: Category[] = [
  "Choose a category",
  "Technology",
  "Artificial Intelligence",
  "Fintech",
  "EdTech",
  "HealthTech",
  "AgriTech",
  "E-commerce",
  "SaaS",
  "Blockchain",
  "Cybersecurity",
  "Biotech",
  "CleanTech",
  "GreenTech",
  "Food & Beverage",
  "Healthcare",
  "Fitness & Wellness",
  "Fashion & Apparel",
  "Logistics & Supply Chain",
  "Real Estate & PropTech",
  "Travel & Tourism",
  "Entertainment & Media",
  "Gaming",
  "Social Impact",
  "AR/VR & Metaverse",
  "Automotive & EV",
  "Robotics",
  "LegalTech",
  "HRTech",
  "Marketplace",
  "Mobility",
  "RetailTech",
  "InsurTech",
  "AdTech",
  "PetTech",
  "SpaceTech",
  "ConstructionTech",
  "SportsTech",
  "Energy",
  "Education",
  "Finance",
  "Others",
];
